name: Tag and release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The current tag
        required: true
        type: String

      java_version:
        description: Version to release
        required: true
        type: choice
        options:
          - java21
          - java17
        default: java17

jobs:
  execution:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Choose Java version
        run: |
          PROJECT_VERSION=$(echo "${{ inputs.tag }}" | sed -E "s/[a-zA-Z\-]+-([1-9]+[0-9]?.[0-9]+.[0-9]+)/\\1/" | xargs )
          echo "PROJECT_VERSION: ${PROJECT_VERSION}"
          if [[ $PROJECT_VERSION =~ ^4.[0-9]+.[0-9]+$ ]]; then
            IS_JAVA_21="true"
          else
            IS_JAVA_21="false"
          fi
          echo "IS_JAVA_21: ${IS_JAVA_21}"
          echo "IS_JAVA_21=${IS_JAVA_21}" >> $GITHUB_ENV

      - name: Set Up JDK 17
        if: ${{ env.IS_JAVA_21 == 'false' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Set Up JDK 21
        if: ${{ env.IS_JAVA_21 == 'true' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          overwrite-settings: false
